name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]  # Change to 'master' if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # or the version you use

      - name: Install dependencies
        run: yarn install

      - name: Build and Deploy
        env:
          GIT_USER: ${{ github.actor }}
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: yarn deploy
